apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: hotrod
    app.kubernetes.io/instance: jaeger
  name: demo-app-hotrod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-app-hotrod
  template:
    metadata:
      labels:
        name: demo-app-hotrod
    spec:
      containers:
      - env:
        - name: JAEGER_AGENT_HOST
          value: jaeger-all-in-one-agent.observability.svc.cluster.local
        - name: JAEGER_AGENT_PORT
          value: "6831"
        image: jaegertracing/example-hotrod:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        name: demo-app-hotrod
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app-hotrod
  name: demo-app-hotrod
  namespace: default
spec:
  ports:
  - name: hotrod
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: demo-app-hotrod
  type: ClusterIP