apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels: 
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers: 
      - name: demo-app
        image: us-central1-docker.pkg.dev/citric-shine-378115/observability-app/observability-app:latest
        imagePullPolicy: Always
        env:
        - name: OTEL_SERVICE_NAME
          value: demo-svc
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: application=demo-app
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://otel-collector.observability.svc.cluster.local:4317
        ports:
        - name: http-port
          containerPort: 8080
        readinessProbe:
          httpGet:  
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10  
          failureThreshold: 2
        livenessProbe:
          httpGet:  
            path: /
            port: http-port
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10 
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app
  name: demo-app
  namespace: default
spec:
  ports:
  - name: app-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP