apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.41.0
    chart: jaeger-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: jaeger
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true