name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "demo-app-2/**"
      - ".github/workflows/build-docker-image-2.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "demo-app-2/**"
      - ".github/workflows/build-docker-image-2.yaml"

concurrency: ${{ github.workflow }}

env:
  PROJECT_ID: citric-shine-378115 # GCP project ID
  GAR_LOCATION: us-central1       # GCP Artifact Registry region
  REPOSITORY: observability-app   # GCP Artifact Registry docker repository naame
  IMAGE_NAME: observability-app   # Docker image name


jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        working-directory: ./demo-app-2
        run: mvn --batch-mode package --file pom.xml
      
      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ./demo-app-2/target/*.jar
          retention-days: 1

  publish:
    name: Publish
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'        # Need for https://github.com/google-github-actions/auth#usage
      id-token: 'write'       # Need for https://github.com/google-github-actions/auth#usage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # Troubleshooting Guide 
        # https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md
      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/234610246542/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider # this is the output provider_name from the TF module
          service_account: gh-workflow-sa@citric-shine-378115.iam.gserviceaccount.com # this is a SA email configured using the TF module with access to YOUR-GCS-BUCKET
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
            name: jar-artifact
            path: demo-app-2/target/

      - name: Push to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: demo-app-2
          push: true
          tags: |
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            "JAR_FILE=./target/spring-boot-web.jar"
