name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "demo-app/**"
  pull_request:
    branches:
      - main
    paths:
      - "demo-app/**"

concurrency: ${{ github.workflow }}

env:
  PROJECT_ID: citric-shine-378115 # GCP project ID
  GAR_LOCATION: us-central1       # GCP Artifact Registry region
  REPOSITORY: observerbility-app  # GCP Artifact Registry docker repository naame
  IMAGE_NAME: observerbility-app  # Docker image name


jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'        # Need for https://github.com/google-github-actions/auth#usage
      id-token: 'write'       # Need for https://github.com/google-github-actions/auth#usage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/234610246542/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: github-action-sa@citric-shine-378115.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Push to Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: demo-app
          push: true
          tags: |
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

