name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "kubernetes-cluster/**"
      - ".github/workflows/create-cluster-and-addons.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "kubernetes-cluster/**"
      - ".github/workflows/create-cluster-and-addons.yaml"

concurrency: ${{ github.workflow }}

jobs:
  setup:
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
          terraform_wrapper: false  # due to https://github.com/gruntwork-io/terragrunt/issues/1202

      - name: Setup Terragrunt
        run: |
          curl -LJO https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.2/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd kubernetes-cluster/environments
          terragrunt run-all apply --auto-approve --terragrunt-non-interactive

      # - name: Terragrunt Destroy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     cd kubernetes-cluster/environments
      #     terragrunt run-all destroy --auto-approve --terragrunt-non-interactive
